### ISSUE TITLE
Email regex shortening

### ISSUE THREAD

**Issue by TankRaj** [sawreeta/email_extraction#1]
https://github.com/sawreeta/email_extraction/blob/21ed6e9a1c12d2442dc06b72ccf2ced51e68caa4/random.php#L4

==> can't this regex be optimized to
 **"[a-zA-Z0-9\\+\\.\\_\\%\\-\\+]{1,256}" +
            "\\@" +
            "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}" +
            "(" +
                "\\." +
                "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25}" +
            ")+"**

???? 
i think this can email pattern

:question:

**Comment by sawreeta** [comment]
Are you sure about this?

**Comment by TankRaj** [comment]
not actually, but this is the library(core) email regex of email on android

**Comment by sawreeta** [comment]
it doesnot work for php ... But can be customized and tried.

**Comment by sawreeta** [comment]
[a-zA-Z0-9\.\_\-\@]{1,256}\@+[a-zA-Z0-9][a-zA-Z0-9]{0,64}(\.+[a-zA-Z0-9][a-zA-Z0-9\-]{0,25})
this regex will work for php . You can test in regextester. If further improvement in regex required you can create issue
